### ISSUE TITLE
DIfferebce between other soft delete projects

### ISSUE THREAD

**Issue by shekarneo** [san4ezy/django_softdelete#2]
Hi, what is the main difference between this and other project like this https://github.com/scoursen/django-softdelete

**Comment by san4ezy** [comment]
Hi! I fluently investigated the project you mentioned. In general this two libs use different approach. 
My implementation works similar as Django's TimeStampedModel (https://github.com/django-extensions/django-extensions/blob/main/django_extensions/db/models.py). Two additional fields will be added to the original object for keeping data about object deletion. In fact, this object not deletes from the database. What are benefits? You still have access to deleted objects if you need (with additional object manager). You can restore soft deleted objects. You can start use this library on fly, your code remains working because the library handles the standard deletion functionality overriding it with soft delete functionality.
Regarding the mentioned library, it keeps the information about this object in his own model through the GenericForeignKey.
There are two radically different approaches. So you should evaluate which is better for your aims.
