### ISSUE TITLE
Error: "The value of 'list_filter[0]' refers to 'is_deleted', which does not refer to a Field." when upgrading to v1

### ISSUE THREAD

**Issue by tomdtp** [san4ezy/django_softdelete#29]
I am in the process of updating our project to django 5 and was trying to upgrade all libraries in the process as well.

However when I upgrade from 0.9.21 to 1.0.12 I cannot start the project anymore, getting the error mentioned in the title.

When I run makemigrations, it generates me the following:

```
  app/migrations/0071_remove_protectedarea_is_deleted_and_more.py
    - Remove field is_deleted from model
    - Add field restored_at to model
```

The class is defined like this:
```
class Model(SoftDeleteModel):
    ...
```

I cannot find any change log or anything documenting why `is_deleted` is replaced with `restored_at`. Is this a bug or a configuration issue? Any input is appreciated.

**Comment by san4ezy** [comment]
Hi @tomdtp 

`is_deleted` was not replaced with `restored_at`. First one was deleted since it's extra field, which could make data inconsistency. Currently the weather of deletion status is reflected in `deleted_at` field, which stores the DateTime stamp if the record was deleted and None otherwise. You could use `deleted_at__isnull` for filtering objects as well.
Regarding second field, `restored_at` works in a similar way, but it reflects the weather of restoring the record.

About your error: it looks like one or more admin classes use the `is_deleted` field for `list_filter` option. Please check you ModelAdmin classes. If you do not use `is_deleted` in your own admin classes, please provide more information so that I can reproduce the situation (traceback, models, admin classes).

**Comment by tomdtp** [comment]
Thank you @san4ezy 

Maybe you can document somewhere that `is_deleted` has been removed in the docs to make this more clear. Problem is resolved by switching to use `deleted_at`.
