### ISSUE TITLE
Question: is this compatible with django-polymorphic?

### ISSUE THREAD

**Issue by ClundXIII** [san4ezy/django_softdelete#49]
Hi,

just a quick question, do you see a reason why this would be incompatible with https://github.com/jazzband/django-polymorphic ?

Cheers,
Simon

**Comment by raizestudio** [comment]
Yes, you may have different issues, let's start with the most basic implementation.

Let's say you have this code:
```
class Parent(PolymorphicModel, SoftDeleteModel):
    title = models.CharField(max_length=255)


class ChildOne(Parent):
    name = models.CharField(max_length=255)


class ChildTwo(Parent):
    name = models.CharField(max_length=255)

```
and then you try to soft delete an instance of `ChildTwo`.

```
child_two = ChildTwo.objects.create(name="test")
child_two.delete()
```
You'll get an error along these line "yourapp.models.ChildOne.DoesNotExist: ChildOne matching query does not exist.", this due to how django-plymorphic handles model inheritance.

There are some workarounds, i generally check if it's a sub class of `PolymorphicModel` and then handle it as i need, you can use `if issubclass(field.related_model, PolymorphicModel):`.

**Comment by ClundXIII** [comment]
all right, thanks for the information.
